"""initial3

Revision ID: 7805eabb5fda
Revises: 23d5b2416f07
Create Date: 2023-12-30 21:23:03.993309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7805eabb5fda'
down_revision = '23d5b2416f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'addresses', ['id_city', 'id_state', 'street_name', 'building_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='unique')
    # ### end Alembic commands ###
