version: '3.8'

services:
  api:
    build: ./api
    restart: always
    ports:
      - 8000:8000
    container_name: api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/facility_booking"
      IN_CONTAINER: 1
    command: "python /app/api.py"
    volumes:
      - ./api:/app


  db:
    image: postgres
    container_name: postgres_db 
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5555:5432
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data 
